load("//:ts.bzl", "ts_library", "ts_test")

ts_library(
    name = "utils",
    srcs = [
        "base64.ts",
        "bytes.ts",
        "env.ts",
        "log.ts",
        "path.ts",
        "query.ts",
        "sleep.ts",
        "uuid.ts",
        "values.ts",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src",
        "//src/core",
        "//src/internal",
    ],
)

ts_test(
    name = "utils_test",
    srcs = [
        "base64.test.ts",
        "path.test.ts",
        "query.test.ts",
    ],
    tsconfig_types = ["node"],
    deps = [
        ":utils",
        "//:node_modules/@types/node",
    ],
)
