load("//:ts.bzl", "ts_library", "ts_test")

ts_library(
    name = "responses",
    srcs = [
        "files.ts",
        "index.ts",
        "responses.ts",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/core",
        "//src/internal",
        "//src/internal/utils",
        "//src/lib",
        "//src/resources",
    ],
)

ts_test(
    name = "responses_test",
    srcs = [
        "files.test.ts",
        "responses.test.ts",
    ],
    deps = [
        ":responses",
        "//src",
    ],
)
