load("//:ts.bzl", "ts_library")

ts_library(
    name = "internal",
    srcs = [
        "builtin-types.ts",
        "errors.ts",
        "headers.ts",
        "parse.ts",
        "request-options.ts",
        "shim-types.ts",
        "shims.ts",
        "to-file.ts",
        "types.ts",
        "uploads.ts",
        "utils.ts",
    ],
    tsconfig_types = ["node"],
    visibility = ["//visibility:public"],
    deps = [
        "//:node_modules/@types/node",
        "//src",
        "//src/core",
        "//src/internal/utils",
    ],
)
